import { docs } from "../../.source/server";
import { loader } from "fumadocs-core/source";

/**
 * Fumadocs source loader — exposes the page tree, slug resolver, and
 * search index used by /docs and /api/search.
 *
 * `.source/` is generated by fumadocs-mdx at build/dev time from MDX
 * files under src/content/docs.
 */
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
